name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  socket_io_client: ^2.0.3+1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2 
  flutter_dotenv: ^6.0.0
  uni_links: ^0.5.1
  http: ^1.1.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.1
  # Optional: Uncomment to enable sound notifications
  # audioplayers: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
